apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataset-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataset-server
  template:
    metadata:
      labels:
        app: dataset-server
    spec:
      containers:
        - name: dataset-server
          image: dataset-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dataset-service
spec:
  type: NodePort
  selector:
    app: dataset-server
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30180  # ใช้สำหรับ dataset
