apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-webapp
  template:
    metadata:
      labels:
        app: react-webapp
    spec:
      containers:
        - name: react-webapp
          image: climate-webapp-page:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-webapp-service
spec:
  type: NodePort
  selector:
    app: react-webapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  

